"""empty message

Revision ID: 591ca682e2d3
Revises: 
Create Date: 2018-11-17 11:32:20.203092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591ca682e2d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EmergencyServicesAPIs',
    sa.Column('EmergencyServiceId', sa.Integer(), nullable=False),
    sa.Column('AreaCode', sa.String(), nullable=False),
    sa.Column('EmergencyServiceSupportsWebAPI', sa.Boolean(), nullable=False),
    sa.Column('EmergencyServiceAPIUrl', sa.String(), nullable=True),
    sa.Column('EmergencyServicePhoneNumber', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('EmergencyServiceId')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Surname', sa.String(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('Password_Hash', sa.String(length=128), nullable=True),
    sa.Column('Birthday', sa.Date(), nullable=False),
    sa.Column('UserPhoneNumber', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BloodPressure',
    sa.Column('BloodPressureUserId', sa.Integer(), nullable=False),
    sa.Column('BloodPressureLowValue', sa.Integer(), nullable=False),
    sa.Column('BloodPressureHighValue', sa.Integer(), nullable=False),
    sa.Column('BloodPressureTimestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['BloodPressureUserId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('BloodPressureUserId')
    )
    op.create_table('Caretakers',
    sa.Column('CaretakerId', sa.Integer(), nullable=False),
    sa.Column('ObservedUserId', sa.Integer(), nullable=False),
    sa.Column('Subscription', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['CaretakerId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('CaretakerId')
    )
    op.create_table('DailySteps',
    sa.Column('DailyStepsId', sa.Integer(), nullable=False),
    sa.Column('StepsValue', sa.Integer(), nullable=False),
    sa.Column('StepsDate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['DailyStepsId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('DailyStepsId')
    )
    op.create_table('HeartRate',
    sa.Column('HeartRateUserId', sa.Integer(), nullable=False),
    sa.Column('HeartRateValue', sa.Integer(), nullable=False),
    sa.Column('HeartRateTimestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['HeartRateUserId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('HeartRateUserId')
    )
    op.create_table('Run',
    sa.Column('RunId', sa.Integer(), nullable=False),
    sa.Column('EventName', sa.String(), nullable=False),
    sa.Column('Description', sa.String(), nullable=False),
    sa.Column('StartTime', sa.DateTime(), nullable=False),
    sa.Column('LocationLat', sa.Float(), nullable=False),
    sa.Column('LocationLong', sa.Float(), nullable=False),
    sa.Column('Public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('OrganizerId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['OrganizerId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('RunId')
    )
    op.create_table('UserSettings',
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('DefaultLocationLat', sa.Float(), nullable=False),
    sa.Column('DefaultLocationLong', sa.Float(), nullable=False),
    sa.Column('AutomatedSOSOn', sa.Boolean(), nullable=False),
    sa.Column('DeveloperAccount', sa.Boolean(), nullable=False),
    sa.Column('AnonymousDataSharingON', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('UserId')
    )
    op.create_table('UsersLocation',
    sa.Column('UsersLocationId', sa.Integer(), nullable=False),
    sa.Column('UserLat', sa.Float(), nullable=False),
    sa.Column('UserLong', sa.Float(), nullable=False),
    sa.Column('LocationUpdateTimestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['UsersLocationId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('UsersLocationId')
    )
    op.create_table('Weight',
    sa.Column('UserIdWeight', sa.Integer(), nullable=False),
    sa.Column('WeightValue', sa.Float(), nullable=False),
    sa.Column('WeightTimestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['UserIdWeight'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('UserIdWeight')
    )
    op.create_table('RunParticipants',
    sa.Column('ParticipantsRunId', sa.Integer(), nullable=False),
    sa.Column('ParticipantsUserId', sa.Integer(), nullable=False),
    sa.Column('DataVisibility', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ParticipantsRunId'], ['Run.RunId'], ),
    sa.ForeignKeyConstraint(['ParticipantsUserId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('ParticipantsRunId', 'ParticipantsUserId')
    )
    op.create_table('RunViewers',
    sa.Column('ViewersRunId', sa.Integer(), nullable=False),
    sa.Column('ViewersUserId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ViewersRunId'], ['Run.RunId'], ),
    sa.ForeignKeyConstraint(['ViewersUserId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('ViewersRunId', 'ViewersUserId')
    )
    op.create_table('RunWaypoints',
    sa.Column('PathRunId', sa.Integer(), nullable=False),
    sa.Column('WaypointIndex', sa.Integer(), nullable=False),
    sa.Column('PathLat', sa.Float(), nullable=False),
    sa.Column('PathLong', sa.Float(), nullable=False),
    sa.Column('OptionalName', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['PathRunId'], ['Run.RunId'], ),
    sa.PrimaryKeyConstraint('PathRunId', 'WaypointIndex')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RunWaypoints')
    op.drop_table('RunViewers')
    op.drop_table('RunParticipants')
    op.drop_table('Weight')
    op.drop_table('UsersLocation')
    op.drop_table('UserSettings')
    op.drop_table('Run')
    op.drop_table('HeartRate')
    op.drop_table('DailySteps')
    op.drop_table('Caretakers')
    op.drop_table('BloodPressure')
    op.drop_table('Users')
    op.drop_table('EmergencyServicesAPIs')
    # ### end Alembic commands ###
