"""empty message

Revision ID: bec0f505c41d
Revises: 591ca682e2d3
Create Date: 2018-11-17 12:02:02.707577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec0f505c41d'
down_revision = '591ca682e2d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'Birthday',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('Users', 'Password_Hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'Password_Hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('Users', 'Birthday',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
